export const dummyAlbums = [
  {
    id: 1,
    title: "Adele 21",
    artist: "Adele",
    image: "https://picsum.photos/400/400?random=7",
  },
  {
    id: 2,
    title: "Scorpion",
    artist: "Drake",
    image: "https://picsum.photos/400/400?random=8",
  },
  {
    id: 3,
    title: "Harry's House",
    artist: "Harry Styles",
    image: "https://picsum.photos/400/400?random=9",
  },
  {
    id: 4,
    title: "Born To Die",
    artist: "Lana Del Rey",
    image: "https://picsum.photos/400/400?random=10",
  },
  {
    id: 5,
    title: "Beauty Behind the...",
    artist: "The Weekend",
    image: "https://picsum.photos/400/400?random=11",
  },
  {
    id: 6,
    title: "Beauty Behind the...",
    artist: "The Weekend",
    image: "https://picsum.photos/400/400?random=11",
  },
  {
    id: 7,
    title: "Beauty Behind the...",
    artist: "The Weekend",
    image: "https://picsum.photos/400/400?random=11",
  },
  {
    id: 8,
    title: "Beauty Behind the...",
    artist: "The Weekend",
    image: "https://picsum.photos/400/400?random=11",
  },
  {
    id: 9,
    title: "Beauty Behind the...",
    artist: "The Weekend",
    image: "https://picsum.photos/400/400?random=11",
  },
  {
    id: 10,
    title: "Beauty Behind the...",
    artist: "The Weekend",
    image: "https://picsum.photos/400/400?random=11",
  },
  {
    id: 11,
    title: "Beauty Behind the...",
    artist: "The Weekend",
    image: "https://picsum.photos/400/400?random=11",
  },
  {
    id: 12,
    title: "Beauty Behind the...",
    artist: "The Weekend",
    image: "https://picsum.photos/400/400?random=11",
  },
  {
    id: 13,
    title: "Beauty Behind the...",
    artist: "The Weekend",
    image: "https://picsum.photos/400/400?random=11",
  },
  {
    id: 14,
    title: "Beauty Behind the...",
    artist: "The Weekend",
    image: "https://picsum.photos/400/400?random=11",
  },
  {
    id: 15,
    title: "Beauty Behind the...",
    artist: "The Weekend",
    image: "https://picsum.photos/400/400?random=11",
  },
];
