export const trendingSongs = [
  {
    id: 1,
    rank: 1,
    title: "Sorfcore",
    artist: "DJ Storm",
    releaseDate: "Nov 4, 2023",
    totalView: 100000,
    duration: "3:26",
    manage: "Edit | Delete",
    image: "https://picsum.photos/400/400?random=1",
  },
  {
    id: 2,
    rank: 2,
    title: "Skyfall Beats",
    artist: "The Soundwave",
    releaseDate: "Oct 26, 2023",
    totalView: 80000,
    duration: "2:45",
    manage: "Edit | Delete",
    image: "https://picsum.photos/400/400?random=2",
  },
  {
    id: 3,
    rank: 3,
    title: "Greedy",
    artist: "Luna Night",
    releaseDate: "Dec 30, 2023",
    totalView: 120000,
    duration: "2:11",
    manage: "Edit | Delete",
    image: "https://picsum.photos/400/400?random=3",
  },
  {
    id: 4,
    rank: 4,
    title: "Lovin On me",
    artist: "Rhythm Kings",
    releaseDate: "Dec 30, 2023",
    totalView: 90000,
    duration: "2:18",
    manage: "Edit | Delete",
    image: "https://picsum.photos/400/400?random=4",
  },
  {
    id: 5,
    rank: 5,
    title: "pain the town red",
    artist: "Electric Storm",
    releaseDate: "Dec 29, 2023",
    totalView: 110000,
    duration: "3:51",
    manage: "Edit | Delete",
    image: "https://picsum.photos/400/400?random=5",
  },
  {
    id: 6,
    rank: 6,
    title: "Dancin On Night",
    artist: "Midnight Groove",
    releaseDate: "may 27, 2023",
    totalView: 130000,
    duration: "2:56",
    manage: "Edit | Delete",
    image: "https://picsum.photos/400/400?random=6",
  },
  {
    id: 7,
    rank: 7,
    title: "Water",
    artist: "Ocean Waves",
    releaseDate: "Dec 10, 2023",
    totalView: 140000,
    duration: "3:20",
    manage: "Edit | Delete",
    image: "https://picsum.photos/400/400?random=7",
  },
  {
    id: 8,
    rank: 8,
    title: "Electric Dreams",
    artist: "Neon Pulse",
    releaseDate: "Nov 15, 2023",
    totalView: 150000,
    duration: "3:42",
    manage: "Edit | Delete",
    image: "https://picsum.photos/400/400?random=8",
  },
  {
    id: 9,
    rank: 9,
    title: "Lost in the Moment",
    artist: "Echo Chamber",
    releaseDate: "Oct 10, 2023",
    totalView: 160000,
    duration: "3:15",
    manage: "Edit | Delete",
    image: "https://picsum.photos/400/400?random=9",
  },
  {
    id: 10,
    rank: 10,
    title: "Fading Away",
    artist: "Whispering Winds",
    releaseDate: "Dec 20, 2023",
    totalView: 170000,
    duration: "3:50",
    manage: "Edit | Delete",
    image: "https://picsum.photos/400/400?random=10",
  },
];
